
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        name: isort (python)
# -   repo: https://github.com/doublify/pre-commit-rust
#     rev: v1.0
#     hooks:
#     -   id: fmt
#     -   id: cargo-check
#     -   id: clippy
- repo: https://github.com/python-poetry/poetry
  rev: '1.2.2'
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: ["--no-update"]
      language_version: 3.11.0
