[workspace]
members = [
  "utils/ftp-export",
  "utils/json2dfasta",
  "utils/json2fasta",
  "utils/rnc-core",
  "utils/rnc-test-utils",
  "utils/rnc-utils",
  "utils/search-export",
  "utils/split-ena",
]
exclude = ["utils/genes-preprocessing", "utils/bed-expander"]

[profile.release]
debug = true
