[tool.poetry]
name = "rnacentral_pipeline"
version = "0.1.0"
description = "The pipeline that imports all RNAcentral data"
authors = ["Blake Sweeney <bsweeney@ebi.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
PyMySQL = "^1.0.2"
attrs = "^21.4.0"
beautifulsoup4 = "^4.10.0"
biopython = "^1.79"
click = "^8.0.3"
click-aliases = "^1.0.1"
furl = "^2.1.3"
gffutils = "^0.10.1"
humanfriendly = "^10.0"
ijson = "^3.1.4"
intervaltree = "^3.1.0"
jsonschema = "^4.3.3"
lxml = "^4.7.1"
more-itertools = "^8.12.0"
obonet = "^0.3.0"
pandas = "^1.3.5"
PyPika = "^0.48.8"
ratelimiter = "^1.2.0"
requests = "^2.27.1"
retry = "^0.9.2"
scikit-learn = "^1.0.2"
semver = "^2.13.0"
sqlitedict = "^1.7.0"
TatSu = "4.4.0"
psycopg2 = "2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
xfail_strict = true
filterwarnings = "ignore::DeprecationWarning"
markers = [
    "slow: Tests that take a long time",
    "db: Test that require access to our database",
]
