CREATE OR REPLACE FUNCTION rnc_test.teardown()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

    EXECUTE 'TRUNCATE TABLE load_rnacentral_all';

    EXECUTE 'ALTER TABLE xref DISABLE CONSTRAINT FK_XREF$CREATED';
    EXECUTE 'ALTER TABLE xref DISABLE CONSTRAINT FK_XREF$DBID';
    EXECUTE 'ALTER TABLE xref DISABLE CONSTRAINT FK_XREF$LAST';
    EXECUTE 'ALTER TABLE xref DISABLE CONSTRAINT FK_XREF$UPI';


    EXECUTE 'ALTER TABLE XREF_PEL_DELETED DISABLE CONSTRAINT XREF_PEL_DELETED_FK1';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED DISABLE CONSTRAINT XREF_PEL_DELETED_FK2';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED DISABLE CONSTRAINT XREF_PEL_DELETED_FK3';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED DISABLE CONSTRAINT XREF_PEL_DELETED_FK4';

    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED DISABLE CONSTRAINT XREF_PEL_NOT_DELETED_FK1';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED DISABLE CONSTRAINT XREF_PEL_NOT_DELETED_FK2';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED DISABLE CONSTRAINT XREF_PEL_NOT_DELETED_FK3';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED DISABLE CONSTRAINT XREF_PEL_NOT_DELETED_FK4';

    EXECUTE 'ALTER TABLE RNACEN.rnc_release DISABLE CONSTRAINT RNC_RELEASE$ID$PK';


    EXECUTE 'TRUNCATE TABLE RNACEN.rnc_release';
    EXECUTE 'TRUNCATE TABLE RNACEN.rna';
    EXECUTE 'TRUNCATE TABLE RNACEN.xref';
    EXECUTE 'TRUNCATE TABLE RNACEN.load_rnacentral';
    EXECUTE 'TRUNCATE TABLE XREF_PEL_DELETED';
    EXECUTE 'TRUNCATE TABLE XREF_PEL_NOT_DELETED';


    EXECUTE 'ALTER TABLE RNACEN.rnc_release ENABLE CONSTRAINT RNC_RELEASE$ID$PK';

    EXECUTE 'ALTER TABLE xref ENABLE CONSTRAINT FK_XREF$CREATED';
    EXECUTE 'ALTER TABLE xref ENABLE CONSTRAINT FK_XREF$DBID';
    EXECUTE 'ALTER TABLE xref ENABLE CONSTRAINT FK_XREF$LAST';

    EXECUTE 'ALTER TABLE xref ENABLE CONSTRAINT FK_XREF$UPI';

    EXECUTE 'ALTER TABLE XREF_PEL_DELETED ENABLE CONSTRAINT XREF_PEL_DELETED_FK1';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED ENABLE CONSTRAINT XREF_PEL_DELETED_FK2';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED ENABLE CONSTRAINT XREF_PEL_DELETED_FK3';
    EXECUTE 'ALTER TABLE XREF_PEL_DELETED ENABLE CONSTRAINT XREF_PEL_DELETED_FK4';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED ENABLE novalidate CONSTRAINT XREF_PEL_NOT_DELETED_FK1';

    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED ENABLE novalidate CONSTRAINT XREF_PEL_NOT_DELETED_FK2';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED ENABLE novalidate CONSTRAINT XREF_PEL_NOT_DELETED_FK3';
    EXECUTE 'ALTER TABLE XREF_PEL_NOT_DELETED ENABLE novalidate CONSTRAINT XREF_PEL_NOT_DELETED_FK4';

  END;

$function$

