#!/bin/bash
# Copyright [2009-2014] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# find directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# remember current directory
STARTING_DIR=`pwd`
# navigate to project's root
cd $DIR # project_root/scripts
cd .. # project_root
RNACENTRAL_HOME_DIR=`pwd`

export PERL5LIB=${RNACENTRAL_HOME_DIR}/rnac-loader/modules:${PERL5LIB}
export PERL5LIB=${RNACENTRAL_HOME_DIR}/rnac-loader/lib/:${PERL5LIB}

export HIVE_USERNAME=""
export HIVE_PASSWORD=""
export HIVE_PORT=""
export HIVE_HOST=""

export ORACLE_USER=""
export ORACLE_PASSWORD=""
export ORACLE_SID=""
export ORACLE_PORT=""
export ORACLE_HOST=""

export DATA_IN=""
export DATA_OUT=""

export DB_RELEASE_TYPE=""
export RNACENTRAL_ADMIN_EMAIL=""
export RNACENTRAL_NO_IMPORT=1 # 0 or 1. When set to 1, do not import the data into the database (useful for development work)

cd $STARTING_DIR
