#!/bin/bash
# Copyright [2009-2014] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


location=/path/to/rnac-loader
export ENSEMBL_CVS_ROOT_DIR=/path/to/ensembl_main
export PERL5LIB=${ENSEMBL_CVS_ROOT_DIR}/ensembl/modules:${PERL5LIB}
export PERL5LIB=${ENSEMBL_CVS_ROOT_DIR}/ensembl-hive/modules:${PERL5LIB}
export PERL5LIB=${location}/rnac-loader/modules:${PERL5LIB}
export PERL5LIB=${location}/rnac-loader/lib/:${PERL5LIB}

export HIVE_USERNAME=""
export HIVE_PASSWORD=""
export HIVE_PORT=""
export HIVE_HOST=""
export ORACLE_USER=""
export ORACLE_PASSWORD=""
export ORACLE_SID=""
export ORACLE_PORT=""
export ORACLE_HOST=""
export DATA_IN=""
export DATA_OUT=""
export DB_RELEASE_TYPE=""
export RNACENTRAL_ADMIN_EMAIL=""
