[package]
name = "json2dfasta"
version = "0.1.0"
authors = ["Blake Sweeney <bsweeney@ebi.ac.uk>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rnc-utils = { path = "../rnc-utils" }
